version: '3'

services:
  spamphibian:
    image: renku/spamphibian:0.0.1
    environment:
      GITLAB_URL: ""
      GITLAB_ACCESS_TOKEN: ""
      SLACK_WEBHOOK_URL: ""
      MODEL_URL: "http://localhost:5001"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      REDIS_PASSWORD: ""
      PYTHONPATH: /app
    depends_on:
      - redis
    ports:
      - "8000:8000"

  model_service:
    image: spamphibian-model:0.0.1
    ports:
      - "5001:5001"
