version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: ""

  spamphibian:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GITLAB_URL: ""
      GITLAB_ACCESS_TOKEN: ""
      SLACK_WEBHOOK_URL: ""
      MODEL_URL: "http://model_service:5001"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      REDIS_PASSWORD: ""
      PYTHONPATH: /app
    depends_on:
      - redis
    ports:
      - "8001:8001"
      - "8000:8000"

  model_service:
    build:
      context: ./models
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
