apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-verified-domains-config
  labels:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  domains.yaml: |
    domains:
      # Global top-level domains
      - "\\.ac\\."  # Academic institutions
      - "\\gov"     # Government institutions
      - "\\edu"     # Educational institutions
