apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spamphibian.fullname" . }}-verified-users-config
  labels:
    app.kubernetes.io/name: {{ include "spamphibian.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    purpose: verified-users
data:
  verified_users.yaml: |
    users:
    {{- range .Values.global.verifiedUsers }}
      - "{{ . }}"
    {{- end }}
