{{- if .Values.global.modelService.enabled -}}
{{- if .Values.global.modelService.imagePullSecrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.modelService.imagePullSecrets.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.global.modelService.imagePullSecrets.dockerConfigJson }}
{{- end }}
{{- end }}
