apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spamphibian.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "spamphibian.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "spamphibian.name" . }}
    spec:
      containers:
      - name: spamphibian
        image: spamphibian:{{ .Chart.AppVersion }}
        env:
        - name: GITLAB_URL
          value: {{ .Values.global.gitlab.url }}
        - name: GITLAB_ACCESS_TOKEN
          value: {{ .Values.global.gitlab.accessToken }}
        - name: SLACK_WEBHOOK_URL
          value: {{ .Values.global.slack.webhookURL }}
        - name: MODEL_URL
          value: "{{ .Values.global.modelService.webhook.hostname }}:{{ .Values.global.modelService.webhook.port }}"
        - name: REDIS_HOST
          value: {{ .Values.global.redis.host }}
        - name: REDIS_PORT
          value: "{{ .Values.global.redis.port }}"
        - name: REDIS_DB
          value: "{{ .Values.global.redis.db }}"
        - name: REDIS_PASSWORD
          value: {{ .Values.global.redis.password }}
        - name: PYTHONPATH
          value: /app
        - name: prometheus_multiproc_dir
          value: prometheus_multiproc_dir
        ports:
        - name: http
          containerPort: 8000
        readinessProbe:
          exec:
            command:
            - /app/check_services_health.sh
          initialDelaySeconds: 10
          periodSeconds: 5
