name: Build & push Helm chart

on:
  push:
    tags:
      - "helm-*"

jobs:
  helm-chart:
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: set up environment variables
        run: |
          echo "GIT_USER=Renku Bot" >> $GITHUB_ENV
          echo "GIT_EMAIL=renku@datascience.ch" >> $GITHUB_ENV
      - name: Set version
        id: vars
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/helm-}"
          echo "tag=$TAG_NAME" >> $GITHUB_ENV
      - name: Push chart and images
        uses: SwissDataScienceCenter/renku-actions/publish-chart@v1.11.3
        env:
          CHART_DIR: helm-chart/
          CHART_NAME: spamphibian
          GIT_USER: chart-bot
          GIT_EMAIL: chart-bot@example.com
          DOCKER_USERNAME: ${{ secrets.RENKU_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.RENKU_DOCKER_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}