name: Build & push Helm chart

on:
  push:
    tags:
      - "helm-*"

jobs:
  helm-chart:
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: tj-actions/branch-names@v8.0.1
        id: branch-names
        with:
          strip_tag_prefix: 'helm-'
      - name: Checking tag value
        run: |
          echo "Tag value: ${{ steps.branch-names.outputs.tag }}"
      - name: Push chart and images
        uses: SwissDataScienceCenter/renku-actions/publish-chart@v1.11.3
        env:
          CHART_DIR: helm-chart/
          CHART_NAME: spamphibian
          GIT_USER: chart-bot
          GIT_EMAIL: chart-bot@example.com
          DOCKER_USERNAME: ${{ secrets.RENKU_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.RENKU_DOCKER_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
    outputs:
      chart-version: ${{ steps.vars.outputs.tag }}