name: Python package

on: [push]

jobs:
  build:
    env:
      PROMETHEUS_MULTIPROC_DIR: prometheus_multiproc_dir

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py39 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py39 .
        continue-on-error: true
      - name: Run pytest on event_service
        run: pytest event_service/test.py

      - name: Run pytest on classification_service
        run: pytest classification_service/test.py

      - name: Run pytest on verification_service
        run: pytest verification_service/test.py

      - name: Run pytest on retrieval_service
        run: pytest retrieval_service/test.py

      - name: Run pytest on notification_service
        run: pytest notification_service/test.py

